name: Sem Release
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.RELEASE_GH_APP_ID }}
        private_key: ${{ secrets.RELEASE_GH_APP_KEY }}

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ steps.generate_token.outputs.token }}

    - name: Setup semantic-release dependency (node.js)
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'

    - name: Setup michael-sem-release-gh-app plugin
      run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog -D

    - name: Push  release
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

        
